# Generated by Django 5.0.4 on 2024-05-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_driver_car_model_alter_driver_email_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
