# Generated by Django 5.0.4 on 2024-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='driver@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
